In [1]:
import meshcat
import meshcat.geometry as g

In [2]:
vis = meshcat.Visualizer()
vis.jupyter_cell()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7006/static/


In [3]:
vis.set_object(g.Box([0.1, 0.1, 0.2]))

In [4]:
vis.delete()

In [8]:
objstring = 'v 0 0 0\nv 10 0 0\nv 5 10 5\nf 1 2 3'
vis.set_object(g.MeshGeometry(objstring, 'obj'))

In [9]:
print(objstring)

v 0 0 0
v 10 0 0
v 5 10 5
f 1 2 3


In [13]:
import numpy as np
from compas.geometry import Point, Frame, Box
from compas_vol.primitives import VolBox

In [11]:
from skimage.measure import marching_cubes_lewiner

In [14]:
box = Box(Frame(Point(0, 0, 0), [1, 0.2, 0.1], [-0.1, 1, 0.1]), 20, 15, 10)
vb = VolBox(box, 2.0)

x, y, z = np.ogrid[-15:15:60j, -15:15:60j, -15:15:60j]
d = vb.get_distance_numpy(x, y, z)

In [23]:
verts, faces, normals, values = marching_cubes_lewiner(d, 0.0, spacing=(0.5,0.5,0.5), step_size=3)

In [24]:
verts.shape

(634, 3)

In [25]:
verts[:10]

array([[ 4.44883156, 15.        , 16.5       ],
       [ 4.5       , 14.74415874, 16.5       ],
       [ 4.5       , 15.        , 15.98831749],
       [ 4.5       , 15.        , 17.04547119],
       [ 4.44883156, 16.5       , 13.5       ],
       [ 4.5       , 16.24415779, 13.5       ],
       [ 4.5       , 16.5       , 12.98831749],
       [ 4.29883194, 16.5       , 15.        ],
       [ 4.5       , 15.49415874, 15.        ],
       [ 4.14883184, 16.5       , 16.5       ]])

In [33]:
for v in verts[:10]:
    print('v %f %f %f' % (v[0], v[1], v[2]))

v 4.448832 15.000000 16.500000
v 4.500000 14.744159 16.500000
v 4.500000 15.000000 15.988317
v 4.500000 15.000000 17.045471
v 4.448832 16.500000 13.500000
v 4.500000 16.244158 13.500000
v 4.500000 16.500000 12.988317
v 4.298832 16.500000 15.000000
v 4.500000 15.494159 15.000000
v 4.148832 16.500000 16.500000


In [37]:
for v in verts[:10]:
    print('v {:.3f} {:.3f} {:.3f}'.format(v[0], v[1], v[2]))

v 4.449 15.000 16.500
v 4.500 14.744 16.500
v 4.500 15.000 15.988
v 4.500 15.000 17.045
v 4.449 16.500 13.500
v 4.500 16.244 13.500
v 4.500 16.500 12.988
v 4.299 16.500 15.000
v 4.500 15.494 15.000
v 4.149 16.500 16.500


In [38]:
for v in faces[:10]:
    print('f {} {} {}'.format(v[0], v[1], v[2]))

f 2 1 0
f 3 0 1
f 6 5 4
f 8 7 4
f 8 4 5
f 7 8 2
f 0 7 2
f 9 7 0
f 0 3 10
f 11 0 10


In [26]:
faces.shape

(1264, 3)

In [27]:
faces[:10]

array([[ 2,  1,  0],
       [ 3,  0,  1],
       [ 6,  5,  4],
       [ 8,  7,  4],
       [ 8,  4,  5],
       [ 7,  8,  2],
       [ 0,  7,  2],
       [ 9,  7,  0],
       [ 0,  3, 10],
       [11,  0, 10]], dtype=int32)

In [21]:
values.shape

(5708,)

In [22]:
values[:10]

array([0.64508647, 0.6450865 , 0.6450865 , 0.6934849 , 0.7152725 ,
       0.7152725 , 0.6450865 , 0.6450865 , 0.6450865 , 0.6450865 ],
      dtype=float32)